[package]
name = "besaz"
version = "0.1.1"
description = "A simple and extensible task runner with user-defined workflows written in Rust"
license = "MIT"
repository = "https://github.com/ManiProjs/besaz.git"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.3", features = ["derive"] }
colored = "3.1.1"
notify = "8.2.0"
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.3"
